// -----------------------------------------------------------------------------
// This file was generated by the Nitro compiler, do not edit manually
// Export date: 2023-11-19T23:47:03.740314814Z
// -----------------------------------------------------------------------------
import * as impl from './impl.ts'
// -----------------------------------------------------------------------------
type Nothing = void;
type Boolean = boolean;
type Byte = number;
type Int = number;
type Char = number;
type Long = bigint;
type Float = number;
type Ptr = number;
type RawArray = number;
type String = number;
type Ref = number;
// -----------------------------------------------------------------------------
export const core = {
   // -------------------------------------------------------------------------
   // From intrinsic.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/lang/intrinsic.nitro(intrinsic.nitro:10)
   // @Extern [lib="core", name="as_type_internal"]
   // fun as_type_internal(Int, Int): Int
   as_type_internal(ptr_to_value: Int, type_id: Int): Int { return impl.as_type_internal(ptr_to_value, type_id); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/lang/intrinsic.nitro(intrinsic.nitro:15)
   // @Extern [lib="core", name="is_type_internal"]
   // fun is_type_internal(Int, Int): Boolean
   is_type_internal(ptr_to_value: Int, type_id: Int): Boolean { return impl.is_type_internal(ptr_to_value, type_id); },
   //
   // -------------------------------------------------------------------------
   // From byte.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/byte.nitro(byte.nitro:11)
   // @Extern [lib="core", name="byte_to_int"]
   // fun to_int(Byte): Int
   byte_to_int(self: Byte): Int { return impl.byte_to_int(self); },
   //
   // -------------------------------------------------------------------------
   // From int.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/int.nitro(int.nitro:201)
   // @Extern [lib="core", name="int_to_long"]
   // fun to_long(Int): Long
   int_to_long(self: Int): Long { return impl.int_to_long(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/int.nitro(int.nitro:205)
   // @Extern [lib="core", name="int_to_byte"]
   // fun to_byte(Int): Byte
   int_to_byte(self: Int): Byte { return impl.int_to_byte(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/int.nitro(int.nitro:209)
   // @Extern [lib="core", name="int_to_string"]
   // fun to_string(Int): String
   int_to_string(self: Int): String { return impl.int_to_string(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/int.nitro(int.nitro:218)
   // @Extern [lib="core", name="int_to_string_in_base"]
   // fun to_string_in_base(Int, Int): String
   int_to_string_in_base(self: Int, radix: Int): String { return impl.int_to_string_in_base(self, radix); },
   //
   // -------------------------------------------------------------------------
   // From long.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/long.nitro(long.nitro:198)
   // @Extern [lib="core", name="long_to_int"]
   // fun to_int(Long): Int
   long_to_int(self: Long): Int { return impl.long_to_int(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/long.nitro(long.nitro:202)
   // @Extern [lib="core", name="long_to_byte"]
   // fun to_byte(Long): Byte
   long_to_byte(self: Long): Byte { return impl.long_to_byte(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/long.nitro(long.nitro:206)
   // @Extern [lib="core", name="long_to_string"]
   // fun to_string(Long): String
   long_to_string(self: Long): String { return impl.long_to_string(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/long.nitro(long.nitro:215)
   // @Extern [lib="core", name="long_to_string_in_base"]
   // fun to_string_in_base(Long, Int): String
   long_to_string_in_base(self: Long, radix: Int): String { return impl.long_to_string_in_base(self, radix); },
   //
   // -------------------------------------------------------------------------
   // From float.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/float.nitro(float.nitro:32)
   // @Extern [lib="core", name="float_rem"]
   // fun rem(Float, Float): Float
   float_rem(self: Float, other: Float): Float { return impl.float_rem(self, other); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/float.nitro(float.nitro:127)
   // @Extern [lib="core", name="float_is_nan"]
   // fun is_nan(Float): Boolean
   float_is_nan(self: Float): Boolean { return impl.float_is_nan(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/float.nitro(float.nitro:131)
   // @Extern [lib="core", name="float_is_finite"]
   // fun is_finite(Float): Boolean
   float_is_finite(self: Float): Boolean { return impl.float_is_finite(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/float.nitro(float.nitro:138)
   // @Extern [lib="core", name="float_is_integer"]
   // fun is_integer(Float): Boolean
   float_is_integer(self: Float): Boolean { return impl.float_is_integer(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/float.nitro(float.nitro:146)
   // @Extern [lib="core", name="float_is_safe_integer"]
   // fun is_safe_integer(Float): Boolean
   float_is_safe_integer(self: Float): Boolean { return impl.float_is_safe_integer(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/primitives/float.nitro(float.nitro:157)
   // @Extern [lib="core", name="float_to_string"]
   // fun to_string(Float): String
   float_to_string(self: Float): String { return impl.float_to_string(self); },
   //
   // -------------------------------------------------------------------------
   // From intrinsic_memory.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/intrinsic_memory.nitro(intrinsic_memory.nitro:4)
   // @Extern [lib="core", name="memory_get_memory"]
   // fun get_memory(): MemoryArena
   memory_get_memory(): Ref { return impl.memory_get_memory(); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/intrinsic_memory.nitro(intrinsic_memory.nitro:17)
   // @Extern [lib="core", name="memory_copy_internal"]
   // fun memory_copy_internal(Int, Int, Int): Nothing
   memory_copy_internal(target: Int, source: Int, len: Int): Nothing { return impl.memory_copy_internal(target, source, len); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/intrinsic_memory.nitro(intrinsic_memory.nitro:21)
   // @Extern [lib="core", name="memory_alloc_trace"]
   // fun memory_alloc_trace(Int, Int): Nothing
   memory_alloc_trace(amount: Int, ptr: Int): Nothing { return impl.memory_alloc_trace(amount, ptr); },
   //
   // -------------------------------------------------------------------------
   // From memory_arena.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:37)
   // @Extern [lib="core", name="memory_copy_within"]
   // fun copy_within(MemoryArena, Ptr<Byte>, Ptr<Byte>, Int): Nothing
   memory_copy_within(self: Ref, dst: Ptr, src: Ptr, byte_len: Int): Nothing { return impl.memory_copy_within(self, dst, src, byte_len); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:41)
   // @Extern [lib="core", name="memory_read_byte"]
   // fun read_byte(MemoryArena, Ptr<Byte>): Byte
   memory_read_byte(self: Ref, ptr: Ptr): Byte { return impl.memory_read_byte(self, ptr); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:45)
   // @Extern [lib="core", name="memory_write_byte"]
   // fun write_byte(MemoryArena, Ptr<Byte>, Byte): Nothing
   memory_write_byte(self: Ref, ptr: Ptr, value: Byte): Nothing { return impl.memory_write_byte(self, ptr, value); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:49)
   // @Extern [lib="core", name="memory_read_int"]
   // fun read_int(MemoryArena, Ptr<Int>): Int
   memory_read_int(self: Ref, ptr: Ptr): Int { return impl.memory_read_int(self, ptr); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:53)
   // @Extern [lib="core", name="memory_write_int"]
   // fun write_int(MemoryArena, Ptr<Int>, Int): Nothing
   memory_write_int(self: Ref, ptr: Ptr, value: Int): Nothing { return impl.memory_write_int(self, ptr, value); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:57)
   // @Extern [lib="core", name="memory_read_float"]
   // fun read_float(MemoryArena, Ptr<Float>): Float
   memory_read_float(self: Ref, ptr: Ptr): Float { return impl.memory_read_float(self, ptr); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:61)
   // @Extern [lib="core", name="memory_write_float"]
   // fun write_float(MemoryArena, Ptr<Float>, Float): Nothing
   memory_write_float(self: Ref, ptr: Ptr, value: Float): Nothing { return impl.memory_write_float(self, ptr, value); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/memory_arena.nitro(memory_arena.nitro:65)
   // @Extern [lib="core", name="memory_dump"]
   // fun dump(MemoryArena): Nothing
   memory_dump(self: Ref): Nothing { return impl.memory_dump(self); },
   //
   // -------------------------------------------------------------------------
   // From ptr.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:12)
   // @Extern [lib="core", name="ptr_ptr_of"]
   // fun ptr_of(#Value): Ptr<#Value>
   ptr_ptr_of(value: Ref): Ptr { return impl.ptr_ptr_of(value); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:21)
   // @Extern [lib="core", name="ptr_ptr_from_address"]
   // fun ptr_from_address(Int): Ptr<#Value>
   ptr_ptr_from_address(address: Int): Ptr { return impl.ptr_ptr_from_address(address); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:31)
   // @Extern [lib="core", name="ptr_as_ref"]
   // fun unsafe_as_ref(Ptr<#Value>): #Value
   ptr_as_ref(self: Ptr): Ref { return impl.ptr_as_ref(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:35)
   // @Extern [lib="core", name="ptr_get_address"]
   // fun get_address(Ptr<#Value>): Int
   ptr_get_address(self: Ptr): Int { return impl.ptr_get_address(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:40)
   // @Extern [lib="core", name="ptr_unsafe_cast"]
   // fun unsafe_cast(Ptr<#Value>): Ptr<#Target>
   ptr_unsafe_cast(self: Ptr): Ptr { return impl.ptr_unsafe_cast(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:46)
   // @Extern [lib="core", name="ptr_write"]
   // fun write(Ptr<Ptr<#Value>>, Ptr<#Value>): Nothing
   ptr_write(self: Ptr, value: Ptr): Nothing { return impl.ptr_write(self, value); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:64)
   // @Extern [lib="core", name="ptr_read"]
   // fun read(Ptr<Ptr<#Value>>): Ptr<#Value>
   ptr_read(self: Ptr): Ptr { return impl.ptr_read(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/memory/ptr.nitro(ptr.nitro:73)
   // @Extern [lib="core", name="ptr_to_raw_array"]
   // fun to_raw_array(Ptr<#Value>): RawArray<#Value>
   ptr_to_raw_array(self: Ptr): RawArray { return impl.ptr_to_raw_array(self); },
   //
   // -------------------------------------------------------------------------
   // From exponential_utils.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:4)
   // @Extern [lib="core", name="math_pow"]
   // fun Math::pow(Float, Float): Float
   math_pow(x: Float, y: Float): Float { return impl.math_pow(x, y); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:8)
   // @Extern [lib="core", name="math_sqrt"]
   // fun Math::sqrt(Float): Float
   math_sqrt(x: Float): Float { return impl.math_sqrt(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:12)
   // @Extern [lib="core", name="math_cbrt"]
   // fun Math::cbrt(Float): Float
   math_cbrt(x: Float): Float { return impl.math_cbrt(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:16)
   // @Extern [lib="core", name="math_exp"]
   // fun Math::exp(Float): Float
   math_exp(x: Float): Float { return impl.math_exp(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:20)
   // @Extern [lib="core", name="math_expm1"]
   // fun Math::expm1(Float): Float
   math_expm1(x: Float): Float { return impl.math_expm1(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:25)
   // @Extern [lib="core", name="math_log"]
   // fun Math::log(Float): Float
   math_log(x: Float): Float { return impl.math_log(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:29)
   // @Extern [lib="core", name="math_log1p"]
   // fun Math::log1p(Float): Float
   math_log1p(x: Float): Float { return impl.math_log1p(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:33)
   // @Extern [lib="core", name="math_log10"]
   // fun Math::log10(Float): Float
   math_log10(x: Float): Float { return impl.math_log10(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/exponential_utils.nitro(exponential_utils.nitro:37)
   // @Extern [lib="core", name="math_log2"]
   // fun Math::log2(Float): Float
   math_log2(x: Float): Float { return impl.math_log2(x); },
   //
   // -------------------------------------------------------------------------
   // From trigonometry_utils.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:4)
   // @Extern [lib="core", name="math_sin"]
   // fun Math::sin(Float): Float
   math_sin(x: Float): Float { return impl.math_sin(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:8)
   // @Extern [lib="core", name="math_sinh"]
   // fun Math::sinh(Float): Float
   math_sinh(x: Float): Float { return impl.math_sinh(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:12)
   // @Extern [lib="core", name="math_asin"]
   // fun Math::asin(Float): Float
   math_asin(x: Float): Float { return impl.math_asin(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:16)
   // @Extern [lib="core", name="math_asinh"]
   // fun Math::asinh(Float): Float
   math_asinh(x: Float): Float { return impl.math_asinh(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:20)
   // @Extern [lib="core", name="math_cos"]
   // fun Math::cos(Float): Float
   math_cos(x: Float): Float { return impl.math_cos(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:24)
   // @Extern [lib="core", name="math_cosh"]
   // fun Math::cosh(Float): Float
   math_cosh(x: Float): Float { return impl.math_cosh(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:28)
   // @Extern [lib="core", name="math_acos"]
   // fun Math::acos(Float): Float
   math_acos(x: Float): Float { return impl.math_acos(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:32)
   // @Extern [lib="core", name="math_acosh"]
   // fun Math::acosh(Float): Float
   math_acosh(x: Float): Float { return impl.math_acosh(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:36)
   // @Extern [lib="core", name="math_tan"]
   // fun Math::tan(Float): Float
   math_tan(x: Float): Float { return impl.math_tan(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:40)
   // @Extern [lib="core", name="math_tanh"]
   // fun Math::tanh(Float): Float
   math_tanh(x: Float): Float { return impl.math_tanh(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:44)
   // @Extern [lib="core", name="math_atan"]
   // fun Math::atan(Float): Float
   math_atan(x: Float): Float { return impl.math_atan(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:48)
   // @Extern [lib="core", name="math_atanh"]
   // fun Math::atanh(Float): Float
   math_atanh(x: Float): Float { return impl.math_atanh(x); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/trigonometry_utils.nitro(trigonometry_utils.nitro:52)
   // @Extern [lib="core", name="math_atan2"]
   // fun Math::atan2(Float, Float): Float
   math_atan2(y: Float, x: Float): Float { return impl.math_atan2(y, x); },
   //
   // -------------------------------------------------------------------------
   // From random.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/math/random.nitro(random.nitro:4)
   // @Extern [lib="core", name="random_get_initial_seed"]
   // fun random_get_initial_seed(): Int
   random_get_initial_seed(): Int { return impl.random_get_initial_seed(); },
   //
   // -------------------------------------------------------------------------
   // From ordering.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/sorting/ordering.nitro(ordering.nitro:58)
   // @Extern [lib="core", name="string_get_ordering_internal"]
   // fun get_ordering_internal(String, String): Int
   string_get_ordering_internal(self: String, other: String): Int { return impl.string_get_ordering_internal(self, other); },
   //
   // -------------------------------------------------------------------------
   // From string.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:42)
   // @Extern [lib="core", name="string_codepoint_len"]
   // fun codepoint_len(String): Int
   string_codepoint_len(self: String): Int { return impl.string_codepoint_len(self); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:46)
   // @Extern [lib="core", name="string_get_codepoint"]
   // fun get_codepoint(String, Int): Int
   string_get_codepoint(self: String, index: Int): Int { return impl.string_get_codepoint(self, index); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:52)
   // @Extern [lib="core", name="string_concat_string"]
   // fun concat(String, String): String
   string_concat_string(self: String, other: String): String { return impl.string_concat_string(self, other); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:56)
   // @Extern [lib="core", name="string_concat_char"]
   // fun concat(String, Char): String
   string_concat_char(self: String, char: Char): String { return impl.string_concat_char(self, char); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:60)
   // @Extern [lib="core", name="string_is_equal"]
   // fun is_equal(String, String): Boolean
   string_is_equal(self: String, other: String): Boolean { return impl.string_is_equal(self, other); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:64)
   // @Extern [lib="core", name="string_is_not_equal"]
   // fun is_not_equal(String, String): Boolean
   string_is_not_equal(self: String, other: String): Boolean { return impl.string_is_not_equal(self, other); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/string/string.nitro(string.nitro:79)
   // @Extern [lib="core", name="string_replace"]
   // fun replace(String, String, String): String
   string_replace(self: String, find: String, replacement: String): String { return impl.string_replace(self, find, replacement); },
   //
   // -------------------------------------------------------------------------
   // From debug.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/debug.nitro(debug.nitro:9)
   // @Extern [lib="core", name="println_string"]
   // fun println(String): String
   println_string(i: String): String { return impl.println_string(i); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/debug.nitro(debug.nitro:13)
   // @Extern [lib="core", name="println_int"]
   // fun println(Int): Int
   println_int(i: Int): Int { return impl.println_int(i); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/debug.nitro(debug.nitro:17)
   // @Extern [lib="core", name="println_long"]
   // fun println(Long): Long
   println_long(i: Long): Long { return impl.println_long(i); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/debug.nitro(debug.nitro:21)
   // @Extern [lib="core", name="println_float"]
   // fun println(Float): Float
   println_float(i: Float): Float { return impl.println_float(i); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/debug.nitro(debug.nitro:25)
   // @Extern [lib="core", name="println_boolean"]
   // fun println(Boolean): Boolean
   println_boolean(i: Boolean): Boolean { return impl.println_boolean(i); },
   //
   // -------------------------------------------------------------------------
   // From logger.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/logger.nitro(logger.nitro:5)
   // @Extern [lib="core", name="logger_get_logger"]
   // fun get_logger(): Logger
   logger_get_logger(): Ref { return impl.logger_get_logger(); },
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/logger.nitro(logger.nitro:27)
   // @Extern [lib="core", name="logger_log"]
   // fun log(Logger, String, String): Nothing
   logger_log(self: Ref, level: String, message: String): Nothing { return impl.logger_log(self, level, message); },
   //
   // -------------------------------------------------------------------------
   // From check.nitro
   // -------------------------------------------------------------------------
   //
   // At /home/cout970/Dev/Kotlin/NitroLang/src/main/nitro/core/debug/check.nitro(check.nitro:11)
   // @Extern [lib="core", name="run_test"]
   // fun run_test(String, String): Boolean
   run_test(internal_function_name: String, test_name: String): Boolean { return impl.run_test(internal_function_name, test_name); },
   //
};
// -----------------------------------------------------------------------------
