#!/usr/bin/env bash
set -e

# cd current directory
cd "$(dirname "$0")"

echo "--- Step 1 ---"

# Create wat version for debugging
wasm2wat --no-check -o output.wat output.wasm
# Run a second time to get check errors and use the first output to debug
wasm2wat -o output.wat output.wasm

# Run the wasm file v0
echo "--- Running wasm file generated by Kotlin compiler ---"
./deno_compiler_v0.ts || exit -1

echo "--- Step 2 ---"

# Create wat version for debugging
wasm2wat --no-check -o output2.wat output2.wasm
# Run a second time to get check errors and use the first output to debug
wasm2wat -o output2.wat output2.wasm

# Run the wasm file v1
echo "--- Running wasm file generated by Nitro compiler ---"
./deno_compiler_v1.ts || exit -1

echo "--- Step 3 ---"

# Create wat version for debugging
wasm2wat --no-check -o output3.wat output3.wasm
# Run a second time to get check errors and use the first output to debug
wasm2wat -o output3.wat output3.wasm

# Run the wasm file v2
echo "--- Running wasm file generated by Nitro compiler ---"
./deno_compiler_v2.ts || exit -1

# Create wat version for debugging
wasm2wat --no-check -o output4.wat output4.wasm
# Run a second time to get check errors and use the first output to debug
wasm2wat -o output4.wat output4.wasm

echo "--- Success ---"