fun a() = "abc ${1234} bc"

include "core:intrinsic.nl"
include "core:boolean.nl"
include "core:int.nl"
include "core:float.nl"
include "core:memory.nl"
include "core:ordering.nl"
include "core:optional.nl"
include "core:result.nl"
include "core:math.nl"
include "core:char.nl"
include "core:string.nl"
include "core:list.nl"
include "core:set.nl"
include "core:map.nl"
include "core:string_map.nl"
include "core:json.nl"
include "core:console.nl"
